create table outbox_message (
    id bigint generated by default as identity primary key,
    message_id uuid not null unique,
    aggregate_type text not null,
    aggregate_id text not null,
    topic text not null,
    partition_key text not null,
    payload jsonb not null,
    headers jsonb not null default '{}'::jsonb,
    status text not null default 'NEW',
    attempts integer not null default 0,
    created_at timestamptz not null default now(),
    next_attempt_at timestamptz not null default now(),
    locked_until timestamptz,
    sent_at timestamptz,
    last_error text,
    constraint outbox_message_status_check
        check (status in ('NEW', 'IN_FLIGHT', 'FAILED', 'SENT', 'DEAD')),
    constraint outbox_message_attempts_check check (attempts >= 0)
);

create index outbox_pending_idx
    on outbox_message (next_attempt_at, id)
    where status in ('NEW', 'FAILED');

create index outbox_expired_lease_idx
    on outbox_message (locked_until, id)
    where status = 'IN_FLIGHT';

create table inbox_message (
    message_id uuid not null,
    consumer text not null,
    processed_at timestamptz not null default now(),
    primary key (message_id, consumer)
);
